### PR TITLE
[Cellular Lib CBMC] CBMC for cellular_common.h and cellular_common_api.h

### PR DESCRIPTION
**Pull request by andysun2015**
*Description of changes:*
- Add CBMC implementation for cellular_common.h and cellular_common_api.h
- Run uncrustify for regarding source code and header file.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by n9wxu — APPROVED** [review]

**Comment by chinglee-iot** [comment]
**Some of the common functions are not fully covered in the CBMC tests**
_Cellular_TranslatePktStatus
_Cellular_CheckLibraryStatus

**Some of the functions are not fully covered in the CBMC tests**
_Cellular_TimeoutAtcmdDataSendSuccessToken
_Cellular_TimeoutAtcmdDataSendRequestWithCallback

**The following functions has error in the report**
Cellular_CommonSocketRegisterClosedCallback
Cellular_CommonSocketRegisterDataReadyCallback
Cellular_CommonSocketRegisterSocketOpenCallback
Cellular_CommonUrcProcessCereg
Cellular_CommonUrcProcessCgreg
Cellular_CommonUrcProcessCreg
Cellular_TimeoutAtcmdDataRecvRequestWithCallback
_Cellular_DataSendWithTimeoutDelayRaw

If these functions are not implemented well please help to indicate.

**Comment by andysun2015** [comment]
> **Some of the common functions are not fully covered in the CBMC tests**
> _Cellular_TranslatePktStatus
> _Cellular_CheckLibraryStatus
> 
**Reply:**
```
We don't need to verify these APIs fully covered each time, just make sure they could be verified in some APIs.
For _Cellular_TranslatePktStatus, you could check Cellular_CommonGetIPAddress/Cellular_CommonRfOn/...
For _Cellular_CheckLibraryStatus, you could check Cellular_CommonATCommandRaw
```
> **Some of the functions are not fully covered in the CBMC tests**
> _Cellular_TimeoutAtcmdDataSendSuccessToken
> _Cellular_TimeoutAtcmdDataSendRequestWithCallback
> 
**Reply:**
For _Cellular_TimeoutAtcmdDataSendSuccessToken:
```
There are following APIs not fully covered:
_Cellular_PktioInit common/src/cellular_pktio.c
_Cellular_PktHandlerInit    common/src/cellular_pkthandler.c
_Cellular_TranslatePktStatus    common/src/cellular_common.c
_Cellular_PktioShutdown common/src/cellular_pktio.c
For _Cellular_PktioInit/_Cellular_PktioShutdown we don't need to cover it because it's in private header file (common/include/private/cellular_pktio_internal.h).
For _Cellular_TranslatePktStatus/_Cellular_CheckLibraryStatus, please check the comment above.
```
For _Cellular_TimeoutAtcmdDataSendRequestWithCallback:
This test case not fully testing successfully, will fix it with coverage.

> **The following functions has error in the report**
> Cellular_CommonSocketRegisterClosedCallback
> Cellular_CommonSocketRegisterDataReadyCallback
> Cellular_CommonSocketRegisterSocketOpenCallback
> Cellular_CommonUrcProcessCereg
> Cellular_CommonUrcProcessCgreg
> Cellular_CommonUrcProcessCreg
> Cellular_TimeoutAtcmdDataRecvRequestWithCallback
> _Cellular_DataSendWithTimeoutDelayRaw
> 
**Reply:**
```
These test cases above will be fixed in next commit.
```
> If these functions are not implemented well please help to indicate.

**Comment by andysun2015** [comment]
Please take a look at this commit to fix the comment.
[https://github.com/FreeRTOS/Lab-Project-FreeRTOS-Cellular-Library/pull/12/commits/0ec5261c213af13141f146e97289c5ea4f56c927](url)

**Review by chinglee-iot — APPROVED** [review]
Thanks for the update.
I can generate the report in my environment without errors.
I also verified the modification with cellular demo projects without problem.

**Review by n9wxu — APPROVED** [review]

**Pull request merged**
